<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <title>Page not found</title>
</head>
<body>
<div class="container mt-5">
    <h1>Page not found</h1>
    <div class="mt-5 mb-3">Oops! something went wrong</div>
    <div>
        <a href="/" class="btn btn-primary mt-3">back</a>
    </div>
</div>
</body>
</html>